steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA' ]
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud auth activate-service-account --key-file=$$GOOGLE_APPLICATION_CREDENTIALS
    gcloud run deploy $SERVICE_NAME --image gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA --platform managed --region $REGION --allow-unauthenticated

images:
- 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
